language: java
sudo: required

jdk:
- oraclejdk8
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/521b6e832a3e037f9fa2
    on_success: change
    on_failure: always
    on_start: never
install:   
- mkdir travis-phantomjs   
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2   
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs   
- export PATH=$PWD/travis-phantomjs:$PATH
script:
- chmod +x ./gradlew
after_success:
- 'if [ ${TRAVIS_PULL_REQUEST} != "false" ]; then exit; fi'
- 'if [ ${TRAVIS_BRANCH} != "master" ]; then exit; fi'
- 'if [[ $(git log --format=%B -n 1 $TRAVIS_COMMIT) == *"[ci ignore]"* ]]; then exit; fi'
- 'BUILD_NUMBER=$(phantomjs buildnumber.js)'
- 'COMMIT_MESSAGE=$(phantomjs commitdata.js ${TRAVIS_COMMIT})'
- 'mv ${HOME}/build/${TRAVIS_REPO_SLUG}/build/libs/MinigameCore-{all,${MGC_API}+${BUILD_NUMBER}}.jar'
- 'curl -v -X POST -d "{\"tag\": \"${BUILD_NUMBER}\",\"message\": \"MinigameCore Build ${BUILD_NUMBER}\",\"object\": \"${TRAVIS_COMMIT}\",\"type\": \"commit\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/tags"'
- 'curl -v -X POST -d "{\"ref\": \"refs/tags/${BUILD_NUMBER}\",\"sha\": \"${TRAVIS_COMMIT}\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/refs"'
- 'curl -v -X POST -d "{\"tag_name\": \"${BUILD_NUMBER}\",\"target_commitish\": \"master\",\"name\": \"MinigameCore Build ${BUILD_NUMBER}\", \"body:\": \"${COMMIT_MESSAGE}\r\n**MinigameCore API:** ${MGC_API}\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/releases"'
- 'curl -v -X POST --data-binary @${HOME}/build/${TRAVIS_REPO_SLUG}/build/libs/MinigameCore-${MGC_API}+${BUILD_NUMBER}.jar --header "Content-Type:application/octet-stream" -u Flibio:${GITHUB_OAUTH} "https://uploads.github.com/repos/MinigameCore/MinigameCore/releases/$(phantomjs getid.js)/assets?name=MinigameCore-${MGC_API}+${BUILD_NUMBER}.jar"'
