language: java
sudo: required

jdk:
- oraclejdk8
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/521b6e832a3e037f9fa2
    on_success: change
    on_failure: always
    on_start: never
install:
- 'wget http://stedolan.github.io/jq/download/linux64/jq'
- 'chmod +x ./jq'
- 'sudo cp jq /usr/bin'
script:
- chmod +x ./gradlew
- gradle build
after_success:
- 'if [ ${TRAVIS_PULL_REQUEST} != "false" ]; then exit; fi'
- 'if [ ${TRAVIS_BRANCH} != "master" ]; then exit; fi'
- 'if [[ $(git log --format=%B -n 1 $TRAVIS_COMMIT) == *"[ci ignore]"* ]]; then exit; fi'
- 'dir'
- 'MGC_API=$(cat apiver.txt)'
- 'echo ${MGC_API}'
- 'BUILD_NUMBER=$(curl "https://api.github.com/repos/minigamecore/minigamecore/tags" | jq ".[0].name" | tr -d "\"")'
- 'BUILD_NUMBER=$((BUILD_NUMBER+1))'
- 'echo "Build Number: ${BUILD_NUMBER}"'
- 'COMMIT_MESSAGE=$(curl "https://api.github.com/repos/minigamecore/minigamecore/commits/${TRAVIS_COMMIT}" | jq ".commit.message" | tr -d "\"")'
- 'echo "Commit Message: ${COMMIT_MESSAGE}"'
- 'echo "Build Directory: ${TRAVIS_BUILD_DIR}"'
- 'mv ${TRAVIS_BUILD_DIR}/build/libs/MinigameCore-{all,${MGC_API}+${BUILD_NUMBER}}.jar'
- 'curl -v -X POST -d "{\"tag\": \"${BUILD_NUMBER}\",\"message\": \"MinigameCore Build ${BUILD_NUMBER}\",\"object\": \"${TRAVIS_COMMIT}\",\"type\": \"commit\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/tags"'
- 'curl -v -X POST -d "{\"ref\": \"refs/tags/${BUILD_NUMBER}\",\"sha\": \"${TRAVIS_COMMIT}\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/refs"'
- 'curl -v -X POST -d "{\"tag_name\": \"${BUILD_NUMBER}\",\"target_commitish\": \"master\",\"name\": \"MinigameCore Build ${BUILD_NUMBER}\", \"body:\": \"${COMMIT_MESSAGE}\r\n**MinigameCore API:** ${MGC_API}\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/releases"'
- 'curl -v -X POST --data-binary @${HOME}/build/${TRAVIS_REPO_SLUG}/build/libs/MinigameCore-${MGC_API}+${BUILD_NUMBER}.jar --header "Content-Type:application/octet-stream" -u Flibio:${GITHUB_OAUTH} "https://uploads.github.com/repos/MinigameCore/MinigameCore/releases/$(curl \"https://api.github.com/repos/minigamecore/minigamecore/releases/latest\" | jq \".id\")/assets?name=MinigameCore-${MGC_API}+${BUILD_NUMBER}.jar"'
