language: java
sudo: required
dist: trusty

jdk:
- oraclejdk8
- openjdk8
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/521b6e832a3e037f9fa2
    on_success: change
    on_failure: always
    on_start: never
install:   
- mkdir travis-phantomjs   
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2   
- tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs   
- export PATH=$PWD/travis-phantomjs:$PATH
script:
- chmod +x ./gradlew
after_success:
- 'if [ ${TRAVIS_PULL_REQUEST} != "false" ]; then exit; fi'
- 'if [ ${TRAVIS_BRANCH} != "master" ]; then exit; fi'
- 'if [[ $(git log --format=%B -n 1 $TRAVIS_COMMIT) == *"build-ignore"* ]]; then exit; fi'
- 'IS_UNSTABLE=`cat travis-unstable.txt`'
- 'TARGET_VER=`cat travis-targetversion.txt`'
- 'CHANGELOG=`cat travis-changelog.txt`'
- 'BUILD_NUMBER=$(phantomjs buildnumber.js ${IS_UNSTABLE} ${TARGET_VER})'
- 'curl -v -X POST -d "{\"tag\": \"${BUILD_NUMBER}\",\"message\": \"MinigameCore Build ${BUILD_NUMBER}\",\"object\": \"${TRAVIS_COMMIT}\",\"type\": \"commit\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/tags"'
- 'curl -v -X POST -d "{\"ref\": \"refs/tags/${BUILD_NUMBER}\",\"sha\": \"${TRAVIS_COMMIT}\"}" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/git/refs"'
- 'curl -v -X POST -d "{\"tag_name\": \"${BUILD_NUMBER}\",\"target_commitish\": \"master\",\"name\": \"MinigameCore Build ${BUILD_NUMBER}\",\"prerelease\": ${IS_UNSTABLE},\"body\": \"${CHANGELOG}\" }" --header "Content-Type:application/json" -u Flibio:${GITHUB_OAUTH} "https://api.github.com/repos/MinigameCore/MinigameCore/releases"'
